#!/usr/bin/env python3
"""Turn bench/results/<tag>/*.json into the Markdown tables used in the README.

    python3 bench/summarize.py eu19_vnni                    # one run
    python3 bench/summarize.py eu19_vnni eu19_q6k --diff    # compare runs

With --diff the second run is shown as a delta against the first, which is how the
model-size and ISA experiments are reported.
"""

import argparse
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from languages import EU24  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(tag, results_dir):
    d = os.path.join(results_dir, tag)
    if not os.path.isdir(d):
        sys.exit("no results for tag '%s' (looked in %s)" % (tag, d))
    out = {}
    meta = None
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".json"):
            continue
        blob = json.load(open(os.path.join(d, fn), encoding="utf-8"))
        out[blob["summary"]["lang"]] = blob["summary"]
        meta = blob["meta"]
    return meta, out


def agg(summaries):
    """Corpus-level WER: total errors over total reference words, not a mean of means."""
    words = sum(s["ref_words"] for s in summaries.values())
    errs = sum(s["wer"] / 100.0 * s["ref_words"] for s in summaries.values())
    audio = sum(s["audio_sec"] for s in summaries.values())
    rtf = sum(s["rtf"] * s["audio_sec"] for s in summaries.values())
    rtf_all = sum(s["rtf_all"] * s["audio_sec"] for s in summaries.values())
    return {
        "wer": 100.0 * errs / words if words else float("nan"),
        "rtf": rtf / audio if audio else float("nan"),
        "rtf_all": rtf_all / audio if audio else float("nan"),
        "clips": sum(s["clips"] for s in summaries.values()),
        "audio_sec": audio,
    }


def fmt(v, nd=2):
    return "n/a" if v is None or (isinstance(v, float) and math.isnan(v)) else ("%.*f" % (nd, v))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tags", nargs="+")
    ap.add_argument("--diff", action="store_true", help="show later tags as deltas vs the first")
    ap.add_argument("--results", default=os.path.join(ROOT, "bench", "results"))
    args = ap.parse_args()

    runs = [(t,) + load(t, args.results) for t in args.tags]
    base_tag, base_meta, base = runs[0]

    print("<!-- generated by bench/summarize.py -->")
    print()
    for tag, meta, _ in runs:
        print("- `%s`: threads=%s isa=%s lm=%s" %
              (tag, meta["threads"], meta["isa"], os.path.basename(meta["lm"])))
    print()

    if args.diff and len(runs) > 1:
        head = ["Language", "WER% " + base_tag] + ["WER% " + t for t, _, _ in runs[1:]] + ["Δ WER"]
        print("| " + " | ".join(head) + " |")
        print("|" + "|".join([":--"] + ["--:"] * (len(head) - 1)) + "|")
        for lang in sorted(base, key=lambda l: base[l]["wer"]):
            row = [EU24.get(lang, ("", lang))[1], fmt(base[lang]["wer"])]
            last = base[lang]["wer"]
            for _, _, other in runs[1:]:
                v = other.get(lang, {}).get("wer")
                row.append(fmt(v))
                last = v if v is not None else last
            row.append("%+.2f" % (last - base[lang]["wer"]) if last is not None else "n/a")
            print("| " + " | ".join(row) + " |")
        for tag, _, s in runs:
            a = agg(s)
            print("\n**%s** — corpus WER %.2f%%, RTF %.3f (compute-only), %d clips / %.0f s audio"
                  % (tag, a["wer"], a["rtf"], a["clips"], a["audio_sec"]))
        return

    for tag, meta, s in runs:
        print("### %s\n" % tag)
        print("| Language | WER% | CER% | RTF | RTF incl. load | Clips |")
        print("|:--|--:|--:|--:|--:|--:|")
        for lang in sorted(s, key=lambda l: s[l]["wer"]):
            r = s[lang]
            print("| %s | %s | %s | %s | %s | %d |" %
                  (r["name"], fmt(r["wer"]), fmt(r["cer"]), fmt(r["rtf"], 3),
                   fmt(r["rtf_all"], 3), r["clips"]))
        a = agg(s)
        print("| **corpus** | **%s** | | **%s** | **%s** | **%d** |" %
              (fmt(a["wer"]), fmt(a["rtf"], 3), fmt(a["rtf_all"], 3), a["clips"]))
        print()


if __name__ == "__main__":
    main()
