#!/usr/bin/env python3
"""Score stored sweep results and render the Markdown tables used in the README.

    python3 bench/summarize.py eu19_vnni                        # one run
    python3 bench/summarize.py eu19_vnni eu_head_q4k --diff     # compare runs
    python3 bench/summarize.py eu19_vnni --normalize basic      # without number spelling

Scoring happens here, from the hypotheses run_asr.py stored, so the normalisation
policy can change without re-running inference. Default is `numbers` -- see
scoring.py for why that is not a cosmetic choice.
"""

import argparse
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from languages import EU24  # noqa: E402
from scoring import can_spell_numbers, score  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(tag, results_dir, numbers):
    d = os.path.join(results_dir, tag)
    if not os.path.isdir(d):
        sys.exit("no results for tag '%s' (looked in %s)" % (tag, d))
    out, meta = {}, None
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".json"):
            continue
        blob = json.load(open(os.path.join(d, fn), encoding="utf-8"))
        meta = blob["meta"]
        lang = blob["summary"]["lang"]
        iso = EU24.get(lang, (lang.split("_")[0], lang))[0]

        we = ww = ce = cc = 0
        audio = compute = total = 0.0
        clips = 0
        for r in blob["records"]:
            if "hyp" not in r:
                continue
            a, b, c, d_ = score(r["ref"], r["hyp"], iso, numbers)
            we += a; ww += b; ce += c; cc += d_
            audio += r["duration"]
            compute += (r.get("compute_ms") or 0.0) / 1000.0
            total += (r.get("total") or 0.0) / 1000.0
            clips += 1
        if not clips:
            continue
        out[lang] = {
            "lang": lang, "name": EU24.get(lang, ("", lang))[1], "iso": iso,
            "clips": clips, "audio_sec": audio, "ref_words": ww,
            "wer": 100.0 * we / ww if ww else float("nan"),
            "cer": 100.0 * ce / cc if cc else float("nan"),
            "rtf": compute / audio if audio else float("nan"),
            "rtf_all": total / audio if audio else float("nan"),
            "word_errors": we,
            "numbers_spelled": bool(numbers and can_spell_numbers(iso)),
        }
    return meta, out


def agg(s):
    """Corpus-level WER: total errors over total reference words, not a mean of means."""
    ww = sum(v["ref_words"] for v in s.values())
    we = sum(v["word_errors"] for v in s.values())
    audio = sum(v["audio_sec"] for v in s.values())
    return {
        "wer": 100.0 * we / ww if ww else float("nan"),
        "rtf": sum(v["rtf"] * v["audio_sec"] for v in s.values()) / audio if audio else float("nan"),
        "rtf_all": sum(v["rtf_all"] * v["audio_sec"] for v in s.values()) / audio if audio else float("nan"),
        "clips": sum(v["clips"] for v in s.values()),
        "audio_sec": audio,
    }


def fmt(v, nd=2):
    return "n/a" if v is None or (isinstance(v, float) and math.isnan(v)) else ("%.*f" % (nd, v))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tags", nargs="+")
    ap.add_argument("--diff", action="store_true", help="show later tags as deltas vs the first")
    ap.add_argument("--normalize", choices=["basic", "numbers"], default="numbers")
    ap.add_argument("--max-wer", type=float, default=None,
                    help="only list languages at or below this WER in the first tag")
    ap.add_argument("--results", default=os.path.join(ROOT, "bench", "results"))
    args = ap.parse_args()

    numbers = args.normalize == "numbers"
    runs = [(t,) + load(t, args.results, numbers) for t in args.tags]
    base_tag, base_meta, base = runs[0]

    keep = sorted(base, key=lambda l: base[l]["wer"])
    if args.max_wer is not None:
        keep = [l for l in keep if base[l]["wer"] <= args.max_wer]

    print("<!-- generated by bench/summarize.py (normalize=%s) -->\n" % args.normalize)
    for tag, meta, _ in runs:
        print("- `%s`: threads=%s isa=%s lm=%s" %
              (tag, meta["threads"], meta["isa"], os.path.basename(meta["lm"])))
    nonum = [base[l]["name"] for l in keep if not base[l]["numbers_spelled"]]
    if numbers and nonum:
        print("\n> No number speller for: %s — those rows use basic normalisation only."
              % ", ".join(nonum))
    print()

    if args.diff and len(runs) > 1:
        cols = [t for t, _, _ in runs]
        print("| Language | " + " | ".join("WER% " + c for c in cols) + " | Δ |")
        print("|:--|" + "--:|" * (len(cols) + 1))
        for lang in keep:
            row = [base[lang]["name"]] + [fmt(r[2].get(lang, {}).get("wer")) for r in runs]
            last = runs[-1][2].get(lang, {}).get("wer")
            row.append("%+.2f" % (last - base[lang]["wer"]) if last is not None else "n/a")
            print("| " + " | ".join(row) + " |")
        print()
        for tag, _, s in runs:
            sub = {k: v for k, v in s.items() if k in keep}
            a = agg(sub)
            print("- **%s** — corpus WER %.2f%%, RTF %.3f, %d clips / %.0f s audio"
                  % (tag, a["wer"], a["rtf"], a["clips"], a["audio_sec"]))
        return

    for tag, meta, s in runs:
        print("### %s\n" % tag)
        print("| Language | WER% | CER% | RTF | RTF incl. load | Clips |")
        print("|:--|--:|--:|--:|--:|--:|")
        for lang in keep:
            r = s.get(lang)
            if not r:
                continue
            print("| %s | %s | %s | %s | %s | %d |" %
                  (r["name"], fmt(r["wer"]), fmt(r["cer"]), fmt(r["rtf"], 3),
                   fmt(r["rtf_all"], 3), r["clips"]))
        a = agg({k: v for k, v in s.items() if k in keep})
        print("| **corpus** | **%s** | | **%s** | **%s** | **%d** |" %
              (fmt(a["wer"]), fmt(a["rtf"], 3), fmt(a["rtf_all"], 3), a["clips"]))
        print()


if __name__ == "__main__":
    main()
